# Generated by Django 6.1.1 on 2026-09-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_language_alter_story_options_remove_book_is_classic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='month_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year_read',
        ),
    ]
