# Generated by Django 6.1.1 on 2026-09-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_month_read_remove_book_year_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_english', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('original_language', models.CharField(blank=True, max_length=64)),
                ('original_quote', models.TextField(blank=True)),
            ],
        ),
    ]
