# Generated by Django 6.1.1 on 2026-09-23 22:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('short_description', models.TextField()),
                ('featured_date', models.DateField(default=datetime.date.today)),
                ('cover_override_url', models.URLField(blank=True, help_text='Optional - paste a direct image URL here to override the automatic Open Library cover')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'ordering': ['-featured_date'],
            },
        ),
    ]
